import Word from './word'

export const irregularVerbs = [
    new Word("be", "[bi]", "was, were", "[wɒz] [wɜː]", "been", "[biːn]", "быть", 1),
    new Word("bear", "[beə]", "bore", "[bɔː]", "born, borne", "[bɔːn] [bɔːn]", "нести, родить", 1, true),
    new Word("beat", "[biːt]", "beat", "[biːt]", "beaten", "[ˈbiːtən]", "бить", 1),
    new Word("become", "[bɪˈkʌm]", "became", "[bɪˈkeɪm]", "become", "[bɪˈkʌm]", "становиться", 1),
    new Word("begin", "[bɪˈɡɪn]", "began", "[bɪˈɡæn]", "begun", "[bɪˈɡʌn]", "начинаться", 1),
    new Word("bend", "[bend]", "bent", "[bent]", "bent", "[bent]", "гнуть", 1, true),
    new Word("bet", "[ˈbet]", "bet", "[ˈbet]", "bet", "[ˈbet]", "держать пари", 1, true),
    new Word("bind", "[baɪnd]", "bound", "[baʊnd]", "bound", "[baʊnd]", "связать", 1, true),
    new Word("bite", "[baɪt]", "bit", "[bɪt]", "bitten", "[ˈbɪtən]", "кусать", 1, true),
    new Word("bleed", "[bliːd]", "bled", "[bled]", "bled", "[bled]", "кровоточить", 1, true),
    new Word("blow", "[bləʊ]", "blew", "[bluː]", "blown", "[bləʊn]", "дуть", 1),
    new Word("break", "[breɪk]", "broke", "[brəʊk]", "broken", "[ˈbrəʊkən]", "ломать(ся)", 1),
    new Word("breed", "[briːd]", "bred", "[bred]", "bred", "[bred]", "выращивать, разводить", 1, true),
    new Word("bring", "[brɪŋ]", "brought", "[ˈbrɔːt]", "brought", "[ˈbrɔːt]", "приносить", 1),
    new Word("build", "[bɪld]", "built", "[bɪlt]", "built", "[bɪlt]", "строить", 1),
    new Word("burn", "[bɜːn]", "burnt", "[bɜːnt] [bɜːnd]", "burnt", "[bɜːnt] [bɜːnd]", "гореть, жечь", 1),
    new Word("burst", "[bɜːst]", "burst", "[bɜːst]", "burst", "[bɜːst]", "разразиться, взорваться", 1, true),
    new Word("buy", "[baɪ]", "bought", "[ˈbɔːt]", "bought", "[ˈbɔːt]", "покупать", 1),
    new Word("cast", "[kɑːst]", "cast", "[kɑːst]", "cast", "[kɑːst]", "кинуть, лить металл", 1, true),
    new Word("catch", "[kætʃ]", "caught", "[ˈkɔːt]", "caught", "[ˈkɔːt]", "ловить, хватать", 1),
    new Word("choose", "[tʃuːz]", "chose", "[tʃəʊz]", "chosen", "[ˈtʃəʊzən]", "выбирать", 1),
    new Word("come", "[kʌm]", "came", "[keɪm]", "come", "[kʌm]", "приходить", 1),
    new Word("cost", "[kɒst]", "cost", "[kɒst]", "cost", "[kɒst]", "стоить", 1),
    new Word("creep", "[kriːp]", "crept", "[krept]", "crept", "[krept]", "ползти", 1, true),
    new Word("cut", "[kʌt]", "cut", "[kʌt]", "cut", "[kʌt]", "резать", 1),
    new Word("deal", "[diːl]", "dealt", "[delt]", "dealt", "[delt]", "иметь дело", 1, true),
    new Word("dig", "[dɪɡ]", "dug", "[dʌɡ]", "dug", "[dʌɡ]", "копать", 1, true),
    new Word("do", "[duː]", "did", "[dɪd]", "done", "[dʌn]", "делать", 1),
    new Word("draw", "[drɔː]", "drew", "[druː]", "drawn", "[drɔːn]", "тащить, рисовать", 1),
    new Word("dream", "[driːm]", "dreamt, dreamed", "[dremt] [driːmd]", "dreamt, dreamed", "[dremt] [driːmd]", "грезить, мечтать", 1, true),
    new Word("drink", "[drɪŋk]", "drank", "[dræŋk]", "drunk", "[drʌŋk]", "пить", 1),
    new Word("drive", "[draɪv]", "drove", "[drəʊv]", "driven", "[ˈdrɪvən]", "везти, гнать", 1),
    new Word("dwell", "[dwel]", "dwelt", "[dwelt]", "dwelt", "[dwelt]", "обитать, задерживаться", 1, true),
    new Word("eat", "[iːt]", "ate", "[et]", "eaten", "[ˈiːtən]", "есть, кушать", 1),
    new Word("fall", "[fɔːl]", "fell", "[ fel]", "fallen", "[ ˈfɔːlən]", "падать", 1),
    new Word("feed", "[fiːd]", "fed", "[fed]", "fed", "[fed]", "кормить", 1, true),
    new Word("feel", "[fiːl]", "felt", "[felt]", "felt", "[felt]", "чувствовать", 1),
    new Word("fight", "[faɪt]", "fought", "[ˈfɔːt]", "fought", "[ˈfɔːt]", "бороться, сражаться", 1),
    new Word("find", "[faɪnd]", "found", "[faʊnd]", "found", "[faʊnd]", "находить", 1),
    new Word("flee", "[fliː]", "fled", "[fled]", "fled", "[fled]", "бежать, спасаться", 1, true),
    new Word("fly", "[flaɪ]", "flew", "[fluː]", "flown", "[fləʊn]", "летать", 1),
    new Word("forbid", "[fəˈbɪd]", "forbad, forbade", "[fəˈbæd] [fəˈbæd]", "forbidden", "[fəˈbɪdən]", "запретить", 1, true),
    new Word("foresee", "[fɔːˈsiː]", "foresaw", "[fɔːˈsɔː]", "foreseen", "[fɔːˈsiːn]", "предвидеть", 1, true),
    new Word("foretell", "[fɔːˈtel]", "foretold", "[fɔːˈtəʊld]", "foretold", "[fɔːˈtəʊld]", "предсказывать", 1, true),
    new Word("forget", "[fəˈɡet]", "forgot", "[fəˈɡɒt]", "forgotten", "[fəˈɡɒtən]", "забывать", 1),
    new Word("forgive", "[fəˈɡɪv]", "forgave", "[fəˈɡeɪv]", "forgiven", "[fəˈɡɪvən]", "прощать", 1),
    new Word("freeze", "[friːz]", "froze", "[frəʊz]", "frozen", "[ˈfrəʊzən]", "замораживать", 1),
    new Word("get", "[ˈɡet]", "got", "[ˈɡɒt]", "got", "[ˈɡɒt]", "получатьж становиться, делаться", 1),
    new Word("give", "[ɡɪv]", "gave", "[ɡeɪv]", "given", "[ɡɪvən]", "давать", 1),
    new Word("go", "[ɡəʊ]", "went", "[ˈwent]", "gone", "[ɡɒn]", "идти, ходить", 1),
    new Word("grind", "[ɡraɪnd]", "ground", "[ɡraʊnd]", "ground", "[ɡraʊnd]", "точить, молоть", 2, true),
    new Word("grow", "[ɡrəʊ]", "grew", "[ɡruː]", "grown", "[ɡrəʊn]", "расти; становиться", 2),
    new Word("hang", "[hæŋ]", "hung, hanged", "[hʌŋ] [hæŋd]", "hung, hanged", "[hʌŋ] [hæŋd]", "висеть, повесить", 2),
    new Word("have", "[hæv]", "had", "[hæd]", "had", "[hæd]", "иметь", 2),
    new Word("hear", "[hɪə]", "heard", "[hɜːd]", "heard", "[hɜːd]", "слушать", 2),
    new Word("hide", "[haɪd]", "hid", "[hɪd]", "hidden", "[ˈhɪdən]", "прятать(ся)", 2, true),
    new Word("hit", "[hɪt]", "hit", "[hɪt]", "hit", "[hɪt]", "ударить, попасть", 2),
    new Word("hold", "[həʊld]", "held", "[held]", "held", "[held]", "держать", 2),
    new Word("hurt", "[hɜːt]", "hurt", "[hɜːt]", "hurt", "[hɜːt]", "причинить боль", 2, true),
    new Word("keep", "[kiːp]", "kept", "[kept]", "kept", "[kept]", "хранить", 2),
    new Word("know", "[nəʊ]", "knew", "[njuː]", "known", "[nəʊn]", "знать", 2),
    new Word("lay", "[leɪ]", "laid", "[leɪd]", "laid", "[leɪd]", "класть, положить", 2),
    new Word("lead", "[liːd]", "led", "[led]", "led", "[led]", "вести", 2),
    new Word("learn", "[lɜːn]", "learnt, learned", "[lɜːnt] [lɜːnd]", "learnt, learned", "[lɜːnt] [lɜːnd]", "учить", 2, true),
    new Word("leave", "[liːv]", "left", "[left]", "left", "[left]", "оставить, покидать", 2),
    new Word("lend", "[lend]", "lent", "[lent]", "lent", "[lent]", "давать взаймы, одолжить", 2),
    new Word("let", "[let]", "let", "[ let]", "let", "[ let]", "позволять, отдавать внаем, пустить, дать", 2),
    new Word("lie", "[laɪ]", "lay", "[leɪ]", "lain", "[leɪn]", "лежать", 2),
    new Word("light", "[laɪt]", "lit, lighted", "[lɪt] [ˈlaɪtɪd]", "lit, lighted", "[lɪt] [ˈlaɪtɪd]", "зажигать, осветить", 2),
    new Word("lose", "[luːz]", "lost", "[lɒst]", "lost", "[lɒst]", "терять", 2),
    new Word("make", "[ˈmeɪk]", "made", "[ˈmeɪd]", "made", "[ˈmeɪd]", "делать", 2),
    new Word("mean", "[miːn]", "meant", "[ment]", "meant", "[ment]", "значить, подразумевать", 2),
    new Word("meet", "[miːt]", "met", "[met]", "met", "[met]", "встретить", 2),
    new Word("mistake", "[mɪˈsteɪk]", "mistook", "[mɪˈstʊk]", "mistaken", "[mɪˈsteɪkən]", "неправильно понимать", 2, true),
    new Word("misunderstand", "[ˌmɪsˌʌndəˈstænd]", "misunderstood", "[ˌmɪsˌʌndəˈstʊd]", "misunderstood", "[ˌmɪsˌʌndəˈstʊd]", "неправильно понимать", 2, true),
    new Word("overcome", "[ˌəʊvəˈkʌm]", "overcame", "[ˌəʊvəˈkeɪm]", "overcome", "[ˌəʊvəˈkʌm]", "преодолевать", 2, true),
    new Word("pay", "[peɪ]", "paid", "[peɪd]", "paid", "[peɪd]", "платить", 2),
    new Word("put", "[ˈpʊt]", "put", "[ˈpʊt]", "put", "[ˈpʊt]", "класть", 2),
    new Word("read", "[riːd]", "read", "[red]", "read", "[red]", "читать", 2),
    new Word("ride", "[raɪd]", "rode", "[rəʊd]", "ridden", "[ˈrɪdən]", "ездить верхом", 2),
    new Word("retell", "[ˌriːˈtel]", "retold", "[ˌriːˈtəʊld]", "retold", "[ˌriːˈtəʊld]", "пересказывать", 2),
    new Word("ring", "[rɪŋ]", "rang", "[ræŋ]", "rung", "[rʌŋ]", "звонить", 2),
    new Word("rise", "[raɪz]", "rose", "[rəʊz]", "risen", "[ˈrɪzən]", "подниматься, подняться", 2),
    new Word("run", "[rʌn]", "ran", "[ræn]", "run", "[rʌn]", "бежать, течь", 2),
    new Word("saw", "[ˈsɔː]", "sawed", "[ˈsɔːd]", "sawn, sawed", "[sɔːn] [ˈsɔːd]", "пилить", 2, true),
    new Word("say", "[ˈseɪ]", "said", "[ˈsed]", "said", "[ˈsed]", "говорить, сказать", 2),
    new Word("see", "[ˈsiː]", "saw", "[ˈsɔː]", "seen", "[ˈsiːn]", "видеть", 2),
    new Word("seek", "[siːk]", "sought", "[ˈsɔːt]", "sought", "[ˈsɔːt]", "искать", 2, true),
    new Word("sell", "[sel]", "sold", "[səʊld]", "sold", "[səʊld]", "продавать", 2),
    new Word("send", "[send]", "sent", "[sent]", "sent", "[sent]", "послать, посылать", 2),
    new Word("set", "[set]", "set", "[set]", "set", "[set]", "устанавливать, помещать, заходить (о солнце)", 2),
    new Word("sew", "[səʊ]", "sewed", "[səʊd]", "sewed, sewn", "[səʊd] [səʊn]", "шить", 2, true),
    new Word("shake", "[ʃeɪk]", "shook", "[ʃʊk]", "shaken", "[ˈʃeɪkən]", "трясти", 3),
    new Word("shine", "[ʃaɪn]", "shone, shined", "[ʃɒn] [ʃaɪnd]", "shone, shined", "[ʃɒn] [ʃaɪnd]", "светить, сиять, блестеть", 3),
    new Word("shoot", "[ʃuːt]", "shot", "[ʃɒt]", "shot", "[ʃɒt]", "стрелять, давать побеги", 3),
    new Word("show", "[ʃəʊ]", "showed", "[ʃəʊd]", "shown, showed", "[ʃəʊn] ʃəʊd]", "показывать", 3, true),
    new Word("shrink", "[ʃrɪŋk]", "shrank", "[ʃræŋk]", "shrunk", "[ʃrʌŋk]", "сокращаться, сжиматься", 3, true),
    new Word("shut", "[ʃʌt]", "shut", "[ʃʌt]", "shut", "[ʃʌt]", "закрывать", 3),
    new Word("sing", "[sɪŋ]", "sang", "[ sæŋ]", "sung", "[ sʌŋ]", "петь", 3),
    new Word("sink", "[sɪŋk]", "sank", "[sæŋk]", "sunk", "[sʌŋk]", "тонуть", 3, true),
    new Word("sit", "[sɪt]", "sat", "[sæt]", "sat", "[sæt]", "сидеть", 3),
    new Word("slay", "[sleɪ]", "slew", "[sluː]", "slain", "[sleɪn]", "убивать", 3, true),
    new Word("sleep", "[sliːp]", "slept", "[slept]", "slept", "[slept]", "спать", 3),
    new Word("slide", "[slaɪd]", "slid", "[slɪd]", "slid", "[slɪd]", "скользить", 3, true),
    new Word("smell", "[smel]", "smelt, smelled", "[smelt] [smeld]", "smelt, smelled", "[smelt] [smeld]", "пахнуть, нюхать", 3, true),
    new Word("speak", "[spiːk]", "spoke", "[spəʊk]", "spoken", "[ˈspəʊkən]", "говорить", 3),
    new Word("spend", "[spend]", "spent", "[spent]", "spent", "[spent]", "тратить, проводить", 3),
    new Word("spit", "[spɪt]", "spat, spit", "[spæt] [spɪt]", "spat, spit", "[spæt] [spɪt]", "плевать", 3, true),
    new Word("split", "[splɪt]", "split", "[splɪt]", "split", "[splɪt]", "расщепить", 3, true),
    new Word("spread", "[spred]", "spread", "[spred]", "spread", "[spred]", "распространяться, распространять", 3),
    new Word("spring", "[sprɪŋ]", "sprang", "[spræŋ]", "sprung", "[sprʌŋ]", "скакать, пружинить", 3, true),
    new Word("stand", "[stænd]", "stood", "[stʊd]", "stood", "[stʊd]", "стоять", 3),
    new Word("steal", "[stiːl]", "stole", "[stəʊl]", "stolen", "[ˈstəʊlən]", "украсть", 3, true),
    new Word("stick", "[stɪk]", "stuck", "[stʌk]", "stuck", "[stʌk]", "уколоть, приклеить, втыкать", 3),
    new Word("sting", "[stɪŋ]", "stung", "[stʌɡ]", "stung", "[stʌɡ]", "ужалить", 3, true),
    new Word("stink", "[stɪŋk]", "stank, stunk", "[stæŋk] [stʌŋk]", "stunk", "[stʌŋk]", "вонять", 3, true),
    new Word("strike", "[straɪk]", "struck", "[strʌk]", "struck", "[strʌk]", "ударить, бить, бастовать, ударять", 3),
    new Word("strive", "[straɪv]", "strove", "[strəʊv]", "striven", "[ˈstrɪvən]", "стараться", 3, true),
    new Word("swear", "[sweə]", "swore", "[swɔː]", "sworn", "[swɔːn]", "клясться, браниться", 3, true),
    new Word("sweep", "[swiːp]", "swept", "[swept]", "swept", "[swept]", "мести, промчаться", 3),
    new Word("swim", "[swɪm]", "swam", "[swæm]", "swum", "[swʌm]", "плыть, плавать", 3),
    new Word("swing", "[swɪŋ]", "swung", "[swʌŋ]", "swung", "[swʌŋ]", "качаться", 3, true),
    new Word("take", "[teɪk]", "took", "[tʊk]", "taken", "[ˈteɪkən]", "взять, брать", 3),
    new Word("teach", "[tiːtʃ]", "taught", "[tɔːt]", "taught", "[tɔːt]", "обучать, учить", 3),
    new Word("tear", "[ˈteə]", "tore", "[ˈtɔː]", "torn", "[ˈtɔːn]", "рвать", 3, true),
    new Word("tell", "[tel]", "told", "[təʊld]", "told", "[təʊld]", "рассказывать, сказать", 3),
    new Word("think", "[ˈθɪŋk]", "thought", "[ˈθɔːt]", "thought", "[ˈθɔːt]", "думать", 3),
    new Word("throw", "[ˈθrəʊ]", "threw", "[θruː]", "thrown", "[ˈθrəʊn]", "бросить, бросать", 3),
    new Word("tread", "[tred]", "trod", "[trɒd]", "trod, trodden", "[trɒd] [ˈtrɒdən]", "ступать", 3, true),
    new Word("understand", "[ˌʌndəˈstænd]", "understood", "[ˌʌndəˈstʊd]", "understood", "[ˌʌndəˈstʊd]", "понимать", 3),
    new Word("wake", "[ weɪk]", "woke, waked", "[wəʊk] [weɪkt]", "woken, waked", "[ˈwəʊkən] [weɪkt]", "просыпаться, будить", 3),
    new Word("wear", "[weə]", "wore", "[wɔː]", "worn", "[wɔːn]", "носить (одежду)", 3),
    new Word("weep", "[wiːp]", "wept", "[wept]", "wept", "[wept]", "плакать", 3),
    new Word("wet", "[wet]", "wet, wetted", "[wet] [ˈwetɪd]", "wet, wetted", "[wet] [ˈwetɪd]", "мочить, увлажнять", 3, true),
    new Word("win", "[wɪn]", "won", "[wʌn]", "won", "[wʌn]", "выиграть, выигрывать, побеждать", 3),
    new Word("wind", "[waɪnd]", "wound", "[waund]", "wound", "[waund]", "заводить (механизм)", 3, true),
    new Word("withdraw", "[wɪðˈdrɔː]", "withdrew", "[wɪðˈdruː]", "withdrawn", "[wɪðˈdrɔːn]", "взять назад, отозвать", 3, true),
    new Word("withstand", "[wɪðˈstænd]", "withstood", "[wɪðˈstʊd]", "withstood", "[wɪðˈstʊd]", "противиться", 3, true),
    new Word("write", "[ˈraɪt]", "wrote", "[rəʊt]", "written", "[ˈrɪtən]", "писать", 3),
];
